import { useMemo, useState } from 'react'
import { Activity, AlertTriangle, Bell, Check, ChevronDown, CloudLightning, Cpu, Database, FileWarning, Gauge, History, Layers3, MapPinned, Menu, Play, Radar, RefreshCw, ShieldCheck, Siren, SlidersHorizontal, Sparkles, ThermometerSun, Waves, X } from 'lucide-react'
import MapView from './components/MapView'
import ChartCard from './components/ChartCard'
import Pipeline from './components/Pipeline'
import ExplainPanel from './components/ExplainPanel'
import { alerts, forecast, places, signals, type Hazard } from './data/mock'

type Page='Overview'|'Live Risk Map'|'Weather Signals'|'Alerts'|'Historical Events'|'Model Insights'|'System Status'
const nav:[Page,typeof Activity][]=[['Overview',Gauge],['Live Risk Map',MapPinned],['Weather Signals',Activity],['Alerts',Siren],['Historical Events',History],['Model Insights',Cpu],['System Status',ShieldCheck]]

function App(){
 const [page,setPage]=useState<Page>('Overview'); const [hour,setHour]=useState(3); const [hazard,setHazard]=useState<Hazard|'All'>('All'); const [showExplain,setShowExplain]=useState(false); const [simulating,setSimulating]=useState(false); const [simStep,setSimStep]=useState(0); const [layers,setLayers]=useState({risk:true,terrain:true,roads:true,population:false,rivers:true}); const [selected,setSelected]=useState<typeof places[number]|null>(null); const [filter,setFilter]=useState('All');
 const fc=forecast[hour]; const currentCloud=fc.cloudburst, currentFlood=fc.flood, currentStorm=fc.storm;
 const visibleAlerts=useMemo(()=>alerts.filter(a=>filter==='All'||a.severity===filter),[filter])
 const runSimulation=()=>{ if(simulating)return; setSimulating(true); setSimStep(0); let s=0; const t=setInterval(()=>{s++;setSimStep(s); if(s>=6){clearInterval(t); setSimulating(false);}},650) }
 const toggle=(k:keyof typeof layers)=>setLayers(v=>({...v,[k]:!v[k]}))
 return <div className="app-shell">
   <aside className="sidebar">
     <div className="brand"><div className="brand-mark"><Siren size={21}/></div><div><strong>VAJRA</strong><span>DYNAMINDS</span></div></div><div className="sih-badge">SIH 2026 <i>•</i> PS 26077</div>
     <div className="nav-label">COMMAND CENTER</div><nav>{nav.map(([label,I])=><button key={label} onClick={()=>setPage(label)} className={page===label?'nav-active':''}><I size={18}/><span>{label}</span>{label==='Alerts'&&<b>3</b>}</button>)}</nav>
     <div className="sidebar-bottom"><div className="engine"><div className="engine-orb"><Cpu size={16}/></div><div><strong>AI Nowcasting Engine</strong><span><i/> ONLINE</span></div></div><div className="proto">PROTOTYPE ENVIRONMENT</div></div>
   </aside>
   <main className="main">
     <header className="topbar"><div className="mobile-brand"><Menu size={20}/><strong>VAJRA</strong></div><div className="title-wrap"><span className="live-dot"/> <div><h1>{page==='Overview'?'Live Severe-Weather Risk Map':page}</h1><p>Rudraprayag District • Uttarakhand</p></div></div><div className="top-actions"><div className="sim-time"><span>SIMULATION TIME</span><strong>06 SEP 2026 • 18:{String(30+hour).padStart(2,'0')} IST</strong></div><button className="icon-btn"><Bell size={18}/><em/></button><button className="location-btn"><MapPinned size={15}/> RUDRAPRAYAG <ChevronDown size={14}/></button></div></header>
     <div className="content">
       {page==='Overview'&&<Overview {...{hour,setHour,hazard,setHazard,layers,toggle,currentCloud,currentFlood,currentStorm,showExplain,setShowExplain,simulating,simStep,runSimulation,selected,setSelected}}/>}
       {page==='Live Risk Map'&&<MapPage {...{hour,setHour,hazard,setHazard,layers,toggle,selected,setSelected,currentCloud,currentFlood,currentStorm}}/>}
       {page==='Weather Signals'&&<SignalsPage/>}
       {page==='Alerts'&&<AlertsPage {...{visibleAlerts,filter,setFilter}}/>}
       {page==='Historical Events'&&<HistoricalPage/>}
       {page==='Model Insights'&&<ModelPage/>}
       {page==='System Status'&&<StatusPage/>}
     </div>
   </main>
   {showExplain&&<ExplainPanel onClose={()=>setShowExplain(false)}/>} 
 </div>
}

function DemoFlag(){return <div className="demo-flag"><Radar size={14}/> DEMO / SIMULATION MODE <span>— Mock values only • not official live measurements</span></div>}
function Overview(p:any){return <><DemoFlag/><section className="hero-grid"><div className="map-panel"><div className="panel-toolbar"><div><div className="kicker">HYPER-LOCAL RISK LAYER</div><h2>Live Hazard Field <span>•</span> 0–6 hour nowcast</h2></div><div className="hazard-tabs">{(['All','Cloudburst','Flash Flood','Thunderstorm'] as const).map(x=><button key={x} className={p.hazard===x?'active':''} onClick={()=>p.setHazard(x)}>{x}</button>)}</div></div><div className="map-wrap"><MapView {...p}/><div className="map-legend"><strong>RISK INTENSITY</strong><span><i className="red"/> HIGH</span><span><i className="orange"/> MODERATE</span><span><i className="yellow"/> WATCH</span></div><div className="layer-stack">{[['risk','Risk'],['terrain','DEM / Terrain'],['roads','Roads'],['population','Population'],['rivers','Rivers']].map(([k,label])=><button key={k} className={p.layers[k]?'on':''} onClick={()=>p.toggle(k)}><Layers3 size={13}/>{label}</button>)}</div></div></div><AlertCard {...p}/></section><section className="below-grid"><Signals strip/><NowcastCard hour={p.hour} setHour={p.setHour} currentCloud={p.currentCloud} currentFlood={p.currentFlood} currentStorm={p.currentStorm}/></section><Pipeline/>{p.simulating&&<SimulationOverlay step={p.simStep}/>}</>}
function AlertCard(p:any){return <div className="alert-panel"><div className="alert-label"><div className="pulse-icon"><AlertTriangle size={19}/></div><span>PRIORITY ALERT <b>ACTIVE</b></span></div><div className="alert-title"><div><div className="kicker">CLOUDBURST RISK</div><h2>Rudraprayag District</h2></div><div className="risk-badge">HIGH</div></div><div className="lead"><span>ESTIMATED LEAD TIME</span><strong>~3 hours</strong></div><div className="trigger-box"><span>TRIGGER SIGNATURE</span><strong>IWV surge + CAPE increase</strong><small>Prototype alert logic</small></div>{[['Cloudburst',p.currentCloud],['Flash Flood',p.currentFlood],['Thunderstorm',p.currentStorm]].map(([n,v])=><div className="prob-row" key={n}><div><span>{n}</span><strong>{v}%</strong></div><div className="progress"><i style={{width:`${v}%`}}/></div></div>)}<div className="alert-actions"><button onClick={()=>p.setShowExplain(true)}><Sparkles size={15}/> View Explainability</button><button onClick={()=>p.setSelected(places[0])} className="ghost"><MapPinned size={15}/> Focus Risk Zone</button></div></div>}
function Signals({strip=false}){return <div className={strip?'signals-strip':''}><div className="section-top"><div><div className="kicker">ATMOSPHERIC STATE</div><h2>Live Atmospheric Signals</h2></div><span className="simulation-chip">SIMULATED</span></div><div className="signals-grid">{signals.map(s=><ChartCard key={s.key} name={s.key==='WCONV'?'Wind Convergence':s.key==='VWS'?'Vertical Wind Shear':s.name} value={s.value} unit={s.unit} trend={s.trend} status={s.status} series={s.series}/>)}</div></div>}
function NowcastCard(p:any){return <div className="nowcast-card"><div className="section-top"><div><div className="kicker">FORECAST EVOLUTION</div><h2>Probability Timeline</h2></div><button className="refresh"><RefreshCw size={14}/></button></div><div className="timeline">{forecast.map((f,i)=><button key={f.hour} className={p.hour===i?'active':''} onClick={()=>p.setHour(i)}><span>{f.label}</span><strong>{f.cloudburst}%</strong></button>)}</div><div className="timeline-chart"><div className="timeline-grid"><span>100</span><span>75</span><span>50</span><span>25</span><span>0</span></div><div className="spark-area"><div className="spark-line cloud">{forecast.map((f,i)=><i key={i} style={{left:`${i*16.66}%`,bottom:`${f.cloudburst}%`}}/>)}</div></div></div><div className="three-prob"><div><span>Cloudburst</span><strong>{p.currentCloud}%</strong></div><div><span>Flash Flood</span><strong>{p.currentFlood}%</strong></div><div><span>Thunderstorm</span><strong>{p.currentStorm}%</strong></div></div></div>}
function MapPage(p:any){return <><DemoFlag/><div className="map-page-grid"><div className="map-panel full"><div className="panel-toolbar"><div><div className="kicker">GIS COMMAND VIEW</div><h2>Hyper-Local Risk Map</h2></div><div className="hazard-tabs">{(['All','Cloudburst','Flash Flood','Thunderstorm'] as const).map(x=><button key={x} className={p.hazard===x?'active':''} onClick={()=>p.setHazard(x)}>{x}</button>)}</div></div><div className="map-wrap large"><MapView {...p}/><div className="map-legend"><strong>RISK INTENSITY</strong><span><i className="red"/> HIGH</span><span><i className="orange"/> MODERATE</span><span><i className="yellow"/> WATCH</span></div></div></div><div className="control-panel"><div className="kicker">LAYER CONTROL</div>{[['risk','Cloudburst / Hazard Zones'],['terrain','DEM / Slope Overlay'],['roads','Road Network'],['population','Population / Vulnerability'],['rivers','Rivers / Drainage']].map(([k,n])=><button key={k} onClick={()=>p.toggle(k)}><span className={p.layers[k]?'switch on':'switch'}/>{n}<Check size={15} className={p.layers[k]?'check-on':'check-off'}/></button>)}<div className="selected-box"><div className="kicker">SELECTED LOCATION</div><h3>{p.selected?.name||'No zone selected'}</h3><p>{p.selected?`${p.selected.hazard} • ${p.selected.level} • ${p.selected.prob}%`:'Click a hazard marker on the map.'}</p></div><NowcastCard {...p}/></div></div></>}
function SignalsPage(){return <><DemoFlag/><Signals/><div className="source-strip"><div><SatelliteIcon/><strong>INSAT-3D/3DR</strong><span>IWV • CTT • rain-linked observations</span></div><div><Database/><strong>IMDAA</strong><span>CAPE • CIN • humidity • winds</span></div><div><MapPinned/><strong>DEM / SRTM</strong><span>Elevation • slope • drainage</span></div></div></>}
function SatelliteIcon(){return <Radar size={18}/>} 
function AlertsPage({visibleAlerts,filter,setFilter}:any){const filters=['All','HIGH','MODERATE','WATCH'];return <><div className="page-intro"><div><div className="kicker">INCIDENT MANAGEMENT</div><h2>Active Alerts & Decision Queue</h2><p>Prioritized hazard signals for district response teams.</p></div><button className="primary-btn"><FileWarning size={16}/> Generate Alert Report</button></div><div className="filterbar">{filters.map(f=><button key={f} className={filter===f?'active':''} onClick={()=>setFilter(f)}><SlidersHorizontal size={14}/>{f}</button>)}</div><div className="table-card"><table><thead><tr><th>Severity</th><th>Event</th><th>Location</th><th>Probability</th><th>Lead Time</th><th>Trigger</th><th>Status</th><th>Action</th></tr></thead><tbody>{visibleAlerts.map((a:any)=><tr key={a.id}><td><span className={`severity ${a.severity.toLowerCase()}`}>{a.severity}</span></td><td><strong>{a.event}</strong></td><td>{a.location}</td><td><strong>{a.prob}%</strong></td><td>{a.lead}</td><td>{a.trigger}</td><td><span className="active-status"><i/> {a.status}</span></td><td><button className="row-btn">View on Map</button><button className="row-btn">Acknowledge</button></td></tr>)}</tbody></table></div><div className="response-card"><div><div className="kicker">RECOMMENDED RESPONSE</div><h3>Consider targeted advisory for high-confidence zones</h3><p>Prototype recommendation layer • Authority action remains human-controlled.</p></div><div className="response-icons"><span><Siren/> Alert</span><span><MapPinned/> Evacuate</span><span><Waves/> Monitor river</span></div></div></>}
function HistoricalPage(){return <><div className="page-intro"><div><div className="kicker">HISTORICAL EVENTS</div><h2>Kedarnath — June 2013</h2><p>Retrospective Prototype Simulation • not a claim of historical prediction.</p></div><span className="retro-chip">RETROSPECTIVE SIMULATION</span></div><div className="history-grid"><div className="history-card"><div className="event-year">2013</div><div className="timeline-events">{[['01','Historical event','Extreme weather episode develops across the Himalayan region.'],['02','Rapid atmospheric evolution','Moisture / instability conditions intensify.'],['03','Extreme rainfall / cloudburst','Very heavy precipitation drives sudden runoff.'],['04','Flash flooding','Terrain-connected flow corridors amplify downstream impact.']].map(([n,t,d])=><div className="history-step" key={n}><span>{n}</span><div><strong>{t}</strong><p>{d}</p></div></div>)}</div></div><div className="how-card"><div className="kicker">HOW VAJRA WOULD ASSIST</div><h3>Target a 2–6 hour nowcasting window</h3><div className="hypo-map"><div className="mountain m1"/><div className="mountain m2"/><div className="river-line"/><div className="hotspot h1"/><div className="hotspot h2"/><span>HYPOTHETICAL RISK FIELD</span></div><p>This simulation demonstrates how the proposed system could represent atmospheric risk together with terrain information.</p><div className="target-box"><Gauge/><div><span>Target warning horizon</span><strong>0–6 hours</strong></div><div><span>Primary value</span><strong>Hyper-local + explainable</strong></div></div></div></div></>}
function ModelPage(){return <><DemoFlag/><Pipeline/><div className="architecture-grid"><div className="arch-card"><div className="kicker">MULTI-HAZARD OUTPUT</div><h3>One fused grid, three hazard probabilities</h3><div className="hazard-output"><div><CloudLightning/><span>Thunderstorm</span><strong>0–6h</strong></div><div><Waves/><span>Cloudburst</span><strong>0–6h</strong></div><div><AlertTriangle/><span>Flash Flood</span><strong>0–6h + DEM</strong></div></div></div><div className="arch-card"><div className="kicker">TECHNICAL POSITIONING</div><h3>Designed for a staged roadmap</h3><p>Prototype today: deterministic mock data. Next stage: curated historical events, model training, validation, calibration, live ingestion, and operational alert interfaces.</p><div className="roadmap"><span><b>01</b> Data readiness</span><span><b>02</b> Model training</span><span><b>03</b> Validation</span><span><b>04</b> Deployment</span></div></div></div></>}
function StatusPage(){const rows=[['Satellite Feed','CONNECTED',Radar],['Atmospheric Data','CONNECTED',Database],['Terrain Data','AVAILABLE',MapPinned],['AI Engine','ONLINE',Cpu],['Risk Mapping','ONLINE',Layers3],['Alert API','ONLINE',Bell],['Dashboard','ONLINE',Activity]] as const;return <><div className="page-intro"><div><div className="kicker">SYSTEM STATUS</div><h2>Prototype Health & Readiness</h2><p>All statuses below are local demo indicators.</p></div><span className="online-badge"><i/> PROTOTYPE ENVIRONMENT</span></div><div className="status-grid">{rows.map(([n,s,I])=><div className="status-card" key={n}><div className="status-icon"><I size={20}/></div><div><span>{n}</span><strong>{s}</strong></div><Check size={18}/></div>)}</div><div className="status-footer"><div><Activity size={17}/><strong>End-to-end demo path</strong><span>Input fusion → nowcast → terrain overlay → explainable alert</span></div><button className="primary-btn"><Play size={15}/> Run System Self-Test</button></div></>}

export default App

function SimulationOverlay({step}:{step:number}){const steps=['Processing satellite frames...','Fusing atmospheric signals...','Running spatiotemporal AI model...','Generating probability maps...','Applying terrain overlay...','Generating explainable alert...'];return <div className="sim-overlay"><div className="sim-modal"><div className="sim-orbit"><Radar size={28}/></div><div className="kicker">VAJRA NOWCAST ENGINE</div><h2>Running simulation</h2><p>Deterministic prototype pipeline • no external APIs required</p><div className="sim-steps">{steps.map((x,i)=><div className={i<step?'done':i===step?'current':''} key={x}><span>{i<step?<Check size={13}/>:i===step?<RefreshCw className="spin" size={13}/>:i+1}</span><span>{x}</span></div>)}</div><div className="sim-progress"><i style={{width:`${Math.min(100,Math.round((step/6)*100))}%`}}/></div></div></div>}
